import { Recipe } from './types';

export interface ProcessImage {
  id: string;
  url: string;
  caption: string;
}

export const sampleRecipes: (Recipe & { processImages?: ProcessImage[] })[] = [
  {
    id: '1',
    slug: 'classic-margherita-pizza',
    title: 'Classic Margherita Pizza',
    description: 'A traditional Italian pizza with fresh San Marzano tomatoes, creamy mozzarella, and fragrant basil leaves on a perfectly crispy crust.',
    coverImage: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=800&q=80',
    ingredients: [
      { id: '1', item: 'Pizza dough', quantity: '500', unit: 'g' },
      { id: '2', item: 'San Marzano tomato sauce', quantity: '200', unit: 'ml' },
      { id: '3', item: 'Fresh mozzarella', quantity: '250', unit: 'g', notes: 'sliced or torn' },
      { id: '4', item: 'Fresh basil leaves', quantity: '10', unit: 'leaves' },
      { id: '5', item: 'Extra virgin olive oil', quantity: '2', unit: 'tbsp' },
      { id: '6', item: 'Sea salt', quantity: 'to taste' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, description: 'Preheat your oven to the highest setting (usually 250-275°C/480-525°F). If you have a pizza stone, place it in the oven to preheat.' },
      { id: '2', stepNumber: 2, description: 'Roll out the pizza dough on a floured surface into a 12-inch circle. The edges should be slightly thicker than the center.' },
      { id: '3', stepNumber: 3, description: 'Spread the tomato sauce evenly over the dough, leaving a 1-inch border for the crust.' },
      { id: '4', stepNumber: 4, description: 'Distribute the mozzarella pieces evenly across the sauce.' },
      { id: '5', stepNumber: 5, description: 'Carefully transfer the pizza to the hot oven and bake for 10-15 minutes until the crust is golden and the cheese is bubbling.' },
      { id: '6', stepNumber: 6, description: 'Remove from oven, add fresh basil leaves, drizzle with olive oil, and season with sea salt. Let rest for 2 minutes before slicing.', tips: 'Add basil after baking to preserve its fresh flavor and vibrant color.' },
    ],
    prepTime: 30,
    cookTime: 15,
    servings: 4,
    difficulty: 'Medium',
    categories: [{ id: '1', name: 'Italian', slug: 'italian' }, { id: '2', name: 'Main Course', slug: 'main-course' }],
    tags: ['pizza', 'vegetarian', 'italian', 'classic'],
    processImages: [
      { id: '1', url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80', caption: 'Kneading the pizza dough' },
      { id: '2', url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80', caption: 'Rolling out the dough' },
      { id: '3', url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80', caption: 'Adding fresh toppings' },
      { id: '4', url: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&q=80', caption: 'Ready for the oven' },
      { id: '5', url: 'https://images.unsplash.com/photo-1604068549290-dea0e4a305ca?w=600&q=80', caption: 'Golden and bubbling' },
    ],
  },
  {
    id: '2',
    slug: 'honey-garlic-salmon',
    title: 'Honey Garlic Glazed Salmon',
    description: 'Succulent salmon fillets glazed with a sweet and savory honey garlic sauce, pan-seared to perfection with crispy skin.',
    coverImage: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80',
    ingredients: [
      { id: '1', item: 'Salmon fillets', quantity: '4', unit: 'pieces', notes: 'skin-on, about 6oz each' },
      { id: '2', item: 'Honey', quantity: '4', unit: 'tbsp' },
      { id: '3', item: 'Garlic cloves', quantity: '4', unit: 'cloves', notes: 'minced' },
      { id: '4', item: 'Soy sauce', quantity: '3', unit: 'tbsp' },
      { id: '5', item: 'Lemon juice', quantity: '2', unit: 'tbsp' },
      { id: '6', item: 'Butter', quantity: '2', unit: 'tbsp' },
      { id: '7', item: 'Fresh parsley', quantity: '2', unit: 'tbsp', notes: 'chopped' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, description: 'Pat salmon fillets dry with paper towels and season with salt and pepper on both sides.' },
      { id: '2', stepNumber: 2, description: 'Mix honey, soy sauce, lemon juice, and minced garlic in a small bowl to create the glaze.' },
      { id: '3', stepNumber: 3, description: 'Heat a large skillet over medium-high heat with a drizzle of oil. Place salmon skin-side up and sear for 4 minutes until golden.' },
      { id: '4', stepNumber: 4, description: 'Flip the salmon to skin-side down. Add butter and pour the honey garlic sauce around the fish.' },
      { id: '5', stepNumber: 5, description: 'Cook for another 3-4 minutes, spooning the sauce over the salmon until cooked through and glazed.', tips: 'The salmon is done when it flakes easily with a fork.' },
      { id: '6', stepNumber: 6, description: 'Garnish with fresh parsley and serve immediately with your favorite sides.' },
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: 'Easy',
    categories: [{ id: '3', name: 'Seafood', slug: 'seafood' }, { id: '2', name: 'Main Course', slug: 'main-course' }],
    tags: ['salmon', 'seafood', 'quick', 'healthy', 'glaze'],
    processImages: [
      { id: '1', url: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600&q=80', caption: 'Fresh salmon fillets' },
      { id: '2', url: 'https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=600&q=80', caption: 'Preparing the honey garlic glaze' },
      { id: '3', url: 'https://images.unsplash.com/photo-1580476262798-bddd9f4b7369?w=600&q=80', caption: 'Searing the salmon' },
      { id: '4', url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600&q=80', caption: 'Glazing with sauce' },
      { id: '5', url: 'https://images.unsplash.com/photo-1485963631004-f2f00b1d6571?w=600&q=80', caption: 'Ready to serve' },
    ],
  },
  {
    id: '3',
    slug: 'thai-green-curry',
    title: 'Authentic Thai Green Curry',
    description: 'A vibrant and aromatic Thai curry with tender chicken, crisp vegetables, and creamy coconut milk infused with fresh green curry paste.',
    coverImage: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800&q=80',
    ingredients: [
      { id: '1', item: 'Chicken breast', quantity: '500', unit: 'g', notes: 'sliced thin' },
      { id: '2', item: 'Green curry paste', quantity: '4', unit: 'tbsp' },
      { id: '3', item: 'Coconut milk', quantity: '400', unit: 'ml' },
      { id: '4', item: 'Bamboo shoots', quantity: '200', unit: 'g' },
      { id: '5', item: 'Thai basil', quantity: '1', unit: 'cup' },
      { id: '6', item: 'Fish sauce', quantity: '2', unit: 'tbsp' },
      { id: '7', item: 'Palm sugar', quantity: '1', unit: 'tbsp' },
      { id: '8', item: 'Thai eggplant', quantity: '100', unit: 'g', notes: 'quartered' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, description: 'Scoop the thick cream from the top of the coconut milk into a hot wok. Stir until it starts to separate and become fragrant.' },
      { id: '2', stepNumber: 2, description: 'Add the green curry paste and fry for 2 minutes until aromatic and the oil separates from the paste.' },
      { id: '3', stepNumber: 3, description: 'Add the sliced chicken and stir-fry until it starts to turn white on the outside, about 3 minutes.' },
      { id: '4', stepNumber: 4, description: 'Pour in the remaining coconut milk, add bamboo shoots and eggplant. Simmer for 10 minutes.' },
      { id: '5', stepNumber: 5, description: 'Season with fish sauce and palm sugar. Adjust to your taste - it should be a balance of salty, sweet, and spicy.' },
      { id: '6', stepNumber: 6, description: 'Add Thai basil leaves, stir once, then remove from heat. Serve hot with jasmine rice.', tips: 'Authentic Thai curries are meant to be quite thin - add more coconut milk if needed.' },
    ],
    prepTime: 20,
    cookTime: 25,
    servings: 4,
    difficulty: 'Medium',
    categories: [{ id: '4', name: 'Thai', slug: 'thai' }, { id: '2', name: 'Main Course', slug: 'main-course' }],
    tags: ['curry', 'thai', 'spicy', 'coconut', 'chicken'],
    processImages: [
      { id: '1', url: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&q=80', caption: 'Fresh Thai ingredients' },
      { id: '2', url: 'https://images.unsplash.com/photo-1625220194771-7ebdea0b70b9?w=600&q=80', caption: 'Making the curry paste' },
      { id: '3', url: 'https://images.unsplash.com/photo-1569058242567-93de6f36f8eb?w=600&q=80', caption: 'Cooking the aromatics' },
      { id: '4', url: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=600&q=80', caption: 'Simmering with coconut milk' },
      { id: '5', url: 'https://images.unsplash.com/photo-1562565652-a0d8f0c59eb4?w=600&q=80', caption: 'Adding fresh Thai basil' },
    ],
  },
  {
    id: '4',
    slug: 'chocolate-lava-cake',
    title: 'Decadent Chocolate Lava Cake',
    description: 'Indulgent individual chocolate cakes with a molten center that flows like lava when you break through the surface.',
    coverImage: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=800&q=80',
    ingredients: [
      { id: '1', item: 'Dark chocolate', quantity: '200', unit: 'g', notes: '70% cocoa' },
      { id: '2', item: 'Unsalted butter', quantity: '120', unit: 'g' },
      { id: '3', item: 'Eggs', quantity: '4', unit: 'large' },
      { id: '4', item: 'Egg yolks', quantity: '4', unit: 'large' },
      { id: '5', item: 'Caster sugar', quantity: '100', unit: 'g' },
      { id: '6', item: 'Plain flour', quantity: '60', unit: 'g' },
      { id: '7', item: 'Cocoa powder', quantity: 'for dusting' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, description: 'Preheat oven to 200°C (400°F). Generously butter 6 ramekins and dust with cocoa powder, tapping out excess.' },
      { id: '2', stepNumber: 2, description: 'Melt chocolate and butter together in a heatproof bowl over simmering water. Stir until smooth, then set aside to cool slightly.' },
      { id: '3', stepNumber: 3, description: 'Whisk eggs, egg yolks, and sugar together until thick and pale - about 5 minutes with an electric mixer.' },
      { id: '4', stepNumber: 4, description: 'Fold the chocolate mixture into the egg mixture gently. Then fold in the flour until just combined.' },
      { id: '5', stepNumber: 5, description: 'Divide the batter evenly among the prepared ramekins. They can be refrigerated for up to 24 hours at this point.', tips: 'If baking from cold, add 2 extra minutes to the baking time.' },
      { id: '6', stepNumber: 6, description: 'Bake for exactly 12-14 minutes until the edges are set but the center still wobbles. Let rest for 1 minute, then invert onto plates and serve immediately with ice cream.' },
    ],
    prepTime: 20,
    cookTime: 14,
    servings: 6,
    difficulty: 'Hard',
    categories: [{ id: '5', name: 'Desserts', slug: 'desserts' }, { id: '6', name: 'French', slug: 'french' }],
    tags: ['chocolate', 'dessert', 'indulgent', 'baking'],
    processImages: [
      { id: '1', url: 'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?w=600&q=80', caption: 'Melting dark chocolate' },
      { id: '2', url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80', caption: 'Whisking the eggs' },
      { id: '3', url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80', caption: 'Folding the batter' },
      { id: '4', url: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=600&q=80', caption: 'Filling the ramekins' },
      { id: '5', url: 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=600&q=80', caption: 'The molten center reveal' },
    ],
  },
  {
    id: '5',
    slug: 'mediterranean-quinoa-bowl',
    title: 'Mediterranean Quinoa Bowl',
    description: 'A nourishing bowl packed with fluffy quinoa, roasted vegetables, creamy hummus, and tangy feta cheese with a lemon herb dressing.',
    coverImage: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    ingredients: [
      { id: '1', item: 'Quinoa', quantity: '200', unit: 'g' },
      { id: '2', item: 'Chickpeas', quantity: '400', unit: 'g', notes: 'canned, drained' },
      { id: '3', item: 'Cherry tomatoes', quantity: '200', unit: 'g', notes: 'halved' },
      { id: '4', item: 'Cucumber', quantity: '1', unit: 'medium', notes: 'diced' },
      { id: '5', item: 'Feta cheese', quantity: '100', unit: 'g', notes: 'crumbled' },
      { id: '6', item: 'Hummus', quantity: '200', unit: 'g' },
      { id: '7', item: 'Kalamata olives', quantity: '50', unit: 'g' },
      { id: '8', item: 'Lemon', quantity: '1', notes: 'juiced' },
      { id: '9', item: 'Extra virgin olive oil', quantity: '3', unit: 'tbsp' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, description: 'Cook quinoa according to package instructions. Usually 1:2 ratio with water, simmer for 15 minutes. Fluff with a fork and let cool.' },
      { id: '2', stepNumber: 2, description: 'Toss chickpeas with 1 tbsp olive oil, salt, and pepper. Roast at 200°C for 20 minutes until crispy.' },
      { id: '3', stepNumber: 3, description: 'Make the dressing: whisk together remaining olive oil, lemon juice, a pinch of salt, and dried oregano.' },
      { id: '4', stepNumber: 4, description: 'Prepare all fresh vegetables: halve the tomatoes, dice the cucumber, crumble the feta.' },
      { id: '5', stepNumber: 5, description: 'Assemble the bowls: start with quinoa as the base, then arrange chickpeas, tomatoes, cucumber, and olives in sections.' },
      { id: '6', stepNumber: 6, description: 'Add a generous dollop of hummus, sprinkle with feta, and drizzle with the lemon dressing. Serve immediately or pack for meal prep.', tips: 'This bowl keeps well in the fridge for up to 3 days - just add dressing before serving.' },
    ],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: 'Easy',
    categories: [{ id: '7', name: 'Mediterranean', slug: 'mediterranean' }, { id: '8', name: 'Healthy', slug: 'healthy' }],
    tags: ['quinoa', 'vegetarian', 'healthy', 'meal-prep', 'mediterranean'],
    processImages: [
      { id: '1', url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80', caption: 'Fresh Mediterranean ingredients' },
      { id: '2', url: 'https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600&q=80', caption: 'Cooking fluffy quinoa' },
      { id: '3', url: 'https://images.unsplash.com/photo-1623428187969-5da2dbe3a647?w=600&q=80', caption: 'Roasting the chickpeas' },
      { id: '4', url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80', caption: 'Preparing fresh vegetables' },
      { id: '5', url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80', caption: 'Assembling the bowl' },
    ],
  },
  {
    id: '6',
    slug: 'japanese-ramen',
    title: 'Rich Tonkotsu Ramen',
    description: 'A deeply flavorful Japanese ramen with creamy pork bone broth, tender chashu pork, soft-boiled eggs, and springy noodles.',
    coverImage: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=800&q=80',
    ingredients: [
      { id: '1', item: 'Ramen noodles', quantity: '400', unit: 'g' },
      { id: '2', item: 'Pork belly', quantity: '500', unit: 'g', notes: 'for chashu' },
      { id: '3', item: 'Tonkotsu broth', quantity: '1.5', unit: 'L', notes: 'or rich chicken broth' },
      { id: '4', item: 'Eggs', quantity: '4', notes: 'for ajitama' },
      { id: '5', item: 'Green onions', quantity: '4', unit: 'stalks' },
      { id: '6', item: 'Nori sheets', quantity: '4' },
      { id: '7', item: 'Sesame oil', quantity: '1', unit: 'tbsp' },
      { id: '8', item: 'Soy sauce', quantity: '4', unit: 'tbsp' },
    ],
    instructions: [
      { id: '1', stepNumber: 1, description: 'Make the ajitama (marinated eggs): soft-boil eggs for 6.5 minutes, cool in ice water, peel, and marinate in soy sauce and mirin for at least 4 hours.' },
      { id: '2', stepNumber: 2, description: 'Prepare chashu: roll pork belly tightly and tie with string. Braise in soy sauce, sake, sugar, and water for 2-3 hours until tender.' },
      { id: '3', stepNumber: 3, description: 'Heat the tonkotsu broth until steaming. Season with salt and a splash of soy sauce to taste.' },
      { id: '4', stepNumber: 4, description: 'Cook ramen noodles according to package directions - usually 2-3 minutes for fresh noodles. Do not overcook.' },
      { id: '5', stepNumber: 5, description: 'Slice the chashu pork and halve the marinated eggs. Slice green onions thinly.' },
      { id: '6', stepNumber: 6, description: 'Assemble: place drained noodles in a bowl, ladle hot broth over. Top with chashu, egg half, nori, green onions, and a drizzle of sesame oil. Serve immediately.', tips: 'For best results, warm the bowls before assembling to keep the ramen hot longer.' },
    ],
    prepTime: 30,
    cookTime: 180,
    servings: 4,
    difficulty: 'Hard',
    categories: [{ id: '9', name: 'Japanese', slug: 'japanese' }, { id: '2', name: 'Main Course', slug: 'main-course' }],
    tags: ['ramen', 'japanese', 'soup', 'comfort-food'],
    processImages: [
      { id: '1', url: 'https://images.unsplash.com/photo-1617093727343-374698b1b08d?w=600&q=80', caption: 'Preparing fresh ramen noodles' },
      { id: '2', url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&q=80', caption: 'Simmering the rich broth' },
      { id: '3', url: 'https://images.unsplash.com/photo-1591814468924-caf88d1232e1?w=600&q=80', caption: 'Marinating the soft-boiled eggs' },
      { id: '4', url: 'https://images.unsplash.com/photo-1623341214825-9f4f963727da?w=600&q=80', caption: 'Slicing the chashu pork' },
      { id: '5', url: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e?w=600&q=80', caption: 'Assembling the perfect bowl' },
    ],
  },
];
